version: '3.8'

services:
  control:
    build:
      context: ./cmd/control
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ZDVV_PORT=8080
      - ZDVV_REDIS_ADDR=redis:6379
      - ZDVV_REDIS_PASSWORD=
      - ZDVV_REDIS_DB=0
      - ZDVV_AUTH_SECRET=my-secret-key
    depends_on:
      - redis

  proxy:
    build:
      context: ./cmd/proxy
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - PROXY_CONFIG=config.json
    depends_on:
      - control

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
